FROM miniconda-quantum:23.04

LABEL name="ocean-dev"
LABEL description="Development Environment for D-Wave Ocean"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.8.8
ENV IPYKERNEL_VERSION 5.3.4

# Copy Python requirements
COPY requirements.txt .

# Create environment for D-Wave Ocean
RUN conda create --name ocean --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name ocean pip install -r requirements.txt && \
    conda run --name ocean python -m ipykernel install --user --name ocean --display-name "Ocean"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /workspace && cd /workspace

# Set working directory
WORKDIR /workspace

# Set prompt
RUN echo "export PS1='🐳 \[\033[1;34m\]\W \[\033[1;36m\]$ \[\033[0m\]'" >> ~/.bashrc

# Expose port for Jupyter Lab web access
EXPOSE 9991

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/ocean/bin/jupyter lab \
            --notebook-dir=/workspace --ip='0.0.0.0' --port=9991 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-ocean'"]