app: 
  name: forest
  imageName: forest-dev:21.10
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/pyquil/bin/jupyter lab --notebook-dir=/workspace --ip='0.0.0.0' --port=8887 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /workspace
  persistentStorage: 1Gi

service:
  name: forest
  type: NodePort
  port: 8887
  targetPort: 8887
  nodePort: 30887
  password: jupyter-forest-credentials