app: 
  name: pennylane
  imageName: pennylane-dev:20.10
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/pennylane/bin/jupyter lab --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8883 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /opt/notebooks
  persistentStorage: 1Gi

service:
  name: pennylane
  type: NodePort
  port: 8883
  targetPort: 8883
  nodePort: 30883
  password: jupyter-pennylane-credentials