app: 
  name: cirq
  imageName: cirq-dev:20.06
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/cirq/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8882 --no-browser --allow-root"
  containerMountPath: /opt/notebooks
  persistentStorage: 1Gi

service:
  name: cirq
  type: ClusterIP
  port: 8882
  targetPort: 8882