app: 
  name: myqlm
  imageName: myqlm-dev:20.12
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/myqlm/bin/jupyter lab --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=9992 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /opt/notebooks
  persistentStorage: 1Gi

service:
  name: myqlm
  type: NodePort
  port: 9992
  targetPort: 9992
  nodePort: 30992
  password: jupyter-myqlm-credentials