FROM miniconda-quantum:23.04

LABEL name="cirq-dev"
LABEL description="Development Environment for Google Cirq"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.9.16
ENV IPYKERNEL_VERSION 6.19.2

# Copy Python requirements
COPY requirements.txt .

# Create environment for Google Cirq
RUN conda create --name cirq --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name cirq pip install -r requirements.txt && \
    conda run --name cirq python -m ipykernel install --user --name cirq --display-name "Cirq"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /workspace && cd /workspace

# Set working directory
WORKDIR /workspace

# Set prompt
RUN echo "export PS1='🐳 \[\033[1;34m\]\W \[\033[1;36m\]$ \[\033[0m\]'" >> ~/.bashrc

# Expose port for Jupyter Lab web access
EXPOSE 8882

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/cirq/bin/jupyter lab \
            --notebook-dir=/workspace --ip='0.0.0.0' --port=8882 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-cirq'"]