app: 
  name: pytket
  imageName: pytket-dev:21.10
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/pytket/bin/jupyter lab --notebook-dir=/workspace --ip='0.0.0.0' --port=8889 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /workspace
  persistentStorage: 1Gi

service:
  name: pytket
  type: NodePort
  port: 8889
  targetPort: 8889
  nodePort: 30889
  password: jupyter-pytket-credentials