FROM miniconda-quantum:21.01

LABEL name="myqlm-dev"
LABEL description="Development Environment for Atos myQLM"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_MYQLM_VERSION 3.6.12
ENV IPYKERNEL_VERSION 5.3.4

# Install ImageMagick for Wand
RUN apt-get update && \
    apt-get install --yes libmagickwand-dev

# Copy Python requirements
COPY requirements.txt .

# Create environment for Atos myQLM
RUN conda create --name myqlm --yes python=$PYTHON_MYQLM_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name myqlm pip install -r requirements.txt && \
    conda run --name myqlm python -m qat.magics.install && \
    conda run --name myqlm python -m ipykernel install --user --name myqlm --display-name "myQLM"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /workspace && cd /workspace

# Set working directory
WORKDIR /workspace

# Set prompt
RUN echo "export PS1='🐳 \[\033[1;34m\]\W \[\033[1;36m\]$ \[\033[0m\]'" >> ~/.bashrc

# Expose port for Jupyter Lab web access
EXPOSE 9993

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/myqlm/bin/jupyter lab \
            --notebook-dir=/workspace --ip='0.0.0.0' --port=9993 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-myqlm'"]