FROM miniconda-quantum:20.04

LABEL name="qiskit-dev"
LABEL description="Development Environment for IBM Qiskit"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.6
ENV IPYKERNEL_VERSION 5.1.4
ENV QISKIT_VERSION 0.18.3

# Create environment for IBM Qiskit
RUN conda create --name qiskit --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION
RUN conda run --name qiskit pip install qiskit==$QISKIT_VERSION
RUN conda run --name qiskit python -m ipykernel install --user --name qiskit --display-name "Qiskit"

# Clean Conda installation
RUN conda clean --yes --all

# Expose port for Jupyter Notebook web access
EXPOSE 8881

# Set working directory
WORKDIR /opt/notebooks

# Define default command to start bash
CMD ["bash"]