app: 
  name: forest
  imageName: forest-dev:20.06
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/pyquil/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8887 --no-browser --allow-root"
  containerMountPath: /opt/notebooks
  persistentStorage: 1Gi

service:
  name: forest
  type: NodePort
  port: 8887
  targetPort: 8887
  nodePort: 30887