FROM miniconda-quantum:23.04

LABEL name="qiskit-dev"
LABEL description="Development Environment for IBM Qiskit"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.9.16
ENV IPYKERNEL_VERSION 6.19.2

# Copy Python requirements
COPY requirements.txt .

# Create environment for IBM Qiskit
RUN conda create --name qiskit --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name qiskit pip install -r requirements.txt && \
    conda run --name qiskit python -m ipykernel install --user --name qiskit --display-name "Qiskit"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /workspace && cd /workspace

# Set working directory
WORKDIR /workspace

# Set prompt
RUN echo "export PS1='🐳 \[\033[1;34m\]\W \[\033[1;36m\]$ \[\033[0m\]'" >> ~/.bashrc

# Expose port for Jupyter Lab web access
EXPOSE 8881

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/qiskit/bin/jupyter lab \
            --notebook-dir=/workspace --ip='0.0.0.0' --port=8881 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-qiskit'"]