FROM miniconda-quantum:20.10

LABEL name="pennylane-dev"
LABEL description="Development Environment for Xanadu PennyLane"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.9
ENV IPYKERNEL_VERSION 5.3.4
ENV PENNYLANE_VERSION 0.12.0

# Create environment for Xanadu PennyLane
RUN conda create --name pennylane --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION
RUN conda run --name pennylane pip install --use-feature=2020-resolver pennylane==$PENNYLANE_VERSION
RUN conda run --name pennylane python -m ipykernel install --user --name pennylane --display-name "PennyLane"

# Clean Conda installation
RUN conda clean --yes --all

# Expose port for Jupyter Lab web access
EXPOSE 8883

# Set working directory
WORKDIR /opt/notebooks

# Define default command to start bash
CMD ["bash"]