FROM miniconda-quantum:20.12

LABEL name="cirq-dev"
LABEL description="Development Environment for Google Cirq and Tensorflow Quantum"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.9
ENV IPYKERNEL_VERSION 5.3.4

# Copy Python requirements
COPY requirements.txt .

# Create environment for Google Cirq and Tensorflow Quantum
RUN conda create --name cirq --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name cirq pip install -r requirements.txt && \
    conda run --name cirq python -m ipykernel install --user --name cirq --display-name "Cirq"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /opt/notebooks && cd /opt/notebooks

# Expose port for Jupyter Lab web access
EXPOSE 8882

# Set working directory
WORKDIR /opt/notebooks

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/cirq/bin/jupyter lab \
            --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8882 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-cirq'"]