app: 
  name: strawberryfields
  imageName: strawberryfields-dev:20.10
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/strawberryfields/bin/jupyter lab --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8884 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /opt/notebooks
  persistentStorage: 1Gi

service:
  name: strawberryfields
  type: NodePort
  port: 8884
  targetPort: 8884
  nodePort: 30884
  password: jupyter-strawberryfields-credentials