FROM miniconda-quantum:23.04

LABEL name="forest-dev"
LABEL description="Development Environment for Rigetti Forest SDK"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.9.16
ENV IPYKERNEL_VERSION 5.3.4
ENV FOREST_SDK_VERSION 2.23.0

# Copy Python requirements
COPY requirements.txt .

# Create environment for Rigetti Forest SDK
RUN conda create --name pyquil --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name pyquil pip install -r requirements.txt && \
    conda run --name pyquil python -m ipykernel install --user --name pyquil --display-name "PyQuil"

# Clean Conda installation
RUN conda clean --yes --all

# Install Rigetti Forest SDK
RUN wget http://downloads.rigetti.com/qcs-sdk/forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2 && \
    tar -xf forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2 && \
    apt-get install --yes liblapack-dev libblas-dev libffi-dev libzmq3-dev && \
    bash -c "/forest-sdk-${FOREST_SDK_VERSION}-linux-deb/forest-sdk-${FOREST_SDK_VERSION}-linux-deb.run --quiet --accept --noprogress &> /var/log/forest.log" && \
    rm -Rf /forest-sdk-${FOREST_SDK_VERSION}-linux-deb && \
    rm /forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2
COPY start-qvm.sh /

# Create Jupyter Notebook folder
RUN mkdir /workspace && cd /workspace

# Set working directory
WORKDIR /workspace

# Set prompt
RUN echo "export PS1='🐳 \[\033[1;34m\]\W \[\033[1;36m\]$ \[\033[0m\]'" >> ~/.bashrc

# Expose port for Jupyter Lab web access
EXPOSE 8887

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/pyquil/bin/jupyter lab \
            --notebook-dir=/workspace --ip='0.0.0.0' --port=8887 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-forest'"]