FROM miniconda-quantum:20.12

LABEL name="strawberryfields-dev"
LABEL description="Development Environment for Xanadu Strawberry Fields"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.9
ENV IPYKERNEL_VERSION 5.3.4

# Copy Python requirements
COPY requirements.txt .

# Create environment for Xanadu Strawberry Fields
RUN conda create --name strawberryfields --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name strawberryfields pip install -r requirements.txt && \
    conda run --name strawberryfields python -m ipykernel install --user --name strawberryfields --display-name "Strawberry Fields"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /opt/notebooks && cd /opt/notebooks

# Expose port for Jupyter Lab web access
EXPOSE 8884

# Set working directory
WORKDIR /opt/notebooks

# Define entrypoint
ENTRYPOINT ["/bin/bash", \
            "-c", "/opt/conda/envs/strawberryfields/bin/jupyter lab \
            --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8884 --no-browser \
            --allow-root --NotebookApp.token='quantum-dev-strawberryfields'"]