FROM miniconda-quantum:20.05

LABEL name="forest-dev"
LABEL description="Development Environment for Rigetti Forest SDK"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.6
ENV IPYKERNEL_VERSION 5.1.4
ENV PYQUIL_VERSION 2.19.0
ENV FOREST_SDK_VERSION 2.20.0

# Create environment for Rigetti Forest SDK
RUN conda create --name pyquil --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION
RUN conda run --name pyquil pip install pyquil==$PYQUIL_VERSION
RUN conda run --name pyquil python -m ipykernel install --user --name pyquil --display-name "PyQuil"

# Install Rigetti Forest SDK
RUN wget http://downloads.rigetti.com/qcs-sdk/forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2
RUN tar -xf forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2
RUN apt-get install --yes liblapack-dev libblas-dev libffi-dev libzmq3-dev
RUN bash -c "/forest-sdk-${FOREST_SDK_VERSION}-linux-deb/forest-sdk-${FOREST_SDK_VERSION}-linux-deb.run --quiet --accept --noprogress &> /var/log/forest.log"
RUN rm -Rf /forest-sdk-${FOREST_SDK_VERSION}-linux-deb
RUN rm /forest-sdk-${FOREST_SDK_VERSION}-linux-deb.tar.bz2
COPY start-qvm.sh /

# Clean Conda installation
RUN conda clean --yes --all

# Expose port for Jupyter Notebook web access
EXPOSE 8887

# Set working directory
WORKDIR /opt/notebooks

# Define default command to start bash
CMD ["bash"]