app: 
  name: strawberryfields
  imageName: strawberryfields-dev:23.04
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/strawberryfields/bin/jupyter lab --notebook-dir=/workspace --ip='0.0.0.0' --port=8885 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /workspace
  persistentStorage: 1Gi

service:
  name: strawberryfields
  type: NodePort
  port: 8885
  targetPort: 8885
  nodePort: 30885
  password: jupyter-strawberryfields-credentials