app: 
  name: myqlm
  imageName: myqlm-dev:23.04
  imagePullPolicy: IfNotPresent
  containerCommand: "/opt/conda/envs/myqlm/bin/jupyter lab --notebook-dir=/workspace --ip='0.0.0.0' --port=9993 --no-browser --allow-root --NotebookApp.password=${JUPYTER_PASSWORD}"
  containerMountPath: /workspace
  persistentStorage: 1Gi

service:
  name: myqlm
  type: NodePort
  port: 9993
  targetPort: 9993
  nodePort: 30993
  password: jupyter-myqlm-credentials