FROM miniconda-quantum:20.07

LABEL name="ocean-dev"
LABEL description="Development Environment for D-Wave Ocean"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.6
ENV IPYKERNEL_VERSION 5.1.4
ENV DWAVE_OCEAN_SDK_VERSION 2.2.0

# Create environment for D-Wave Ocean
RUN conda create --name ocean --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION
RUN conda run --name ocean pip install dwave-ocean-sdk==$DWAVE_OCEAN_SDK_VERSION
RUN conda run --name ocean python -m ipykernel install --user --name ocean --display-name "Ocean"

# Clean Conda installation
RUN conda clean --yes --all

# Expose port for Jupyter Notebook web access
EXPOSE 9991

# Set working directory
WORKDIR /opt/notebooks

# Define default command to start bash
CMD ["bash"]