FROM miniconda-quantum:20.10

LABEL name="ocean-dev"
LABEL description="Development Environment for D-Wave Ocean"
LABEL maintainer="Alberto Acuto alberto.acuto@nttdata.com"
LABEL vendor="NTT DATA"

# Set version levels
ENV PYTHON_VERSION 3.7.9
ENV IPYKERNEL_VERSION 5.3.4

# Copy Python requirements
COPY requirements.txt .

# Create environment for D-Wave Ocean
RUN conda create --name ocean --yes python=$PYTHON_VERSION ipykernel=$IPYKERNEL_VERSION && \
    conda run --name ocean pip install -r requirements.txt && \
    conda run --name ocean python -m ipykernel install --user --name ocean --display-name "Ocean"

# Clean Conda installation
RUN conda clean --yes --all

# Create Jupyter Notebook folder
RUN mkdir /opt/notebooks && cd /opt/notebooks

# Expose port for Jupyter Lab web access
EXPOSE 9991

# Set working directory
WORKDIR /opt/notebooks

# Define default command to start bash
CMD ["bash"]